# Generated by Django 3.1.4 on 2020-12-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_propertyphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
