# Generated by Django 3.1.4 on 2020-12-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201221_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo1',
            name='image',
            field=models.ImageField(upload_to='original_images/property/photos/'),
        ),
        migrations.DeleteModel(
            name='Photo2',
        ),
    ]
