# Generated by Django 3.1.4 on 2020-12-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201222_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo1',
            name='image',
            field=models.ImageField(upload_to='property/photos/'),
        ),
    ]
